name: example
description: "An example of using the flutter_picture_taker package."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  flutter_picture_taker:
    path: ../
  gap: ^3.0.1

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  flutter_test:
    sdk: flutter
